# Project information
site_name: Grupo 02
site_description: Artefatos de MDS e EPS, 2020.1
site_author: Grupo 02
site_url: https://fga-eps-mds.github.io/2020.1-Grupo2-wiki/

# Repository
repo_name: Grupo 02
repo_url: https://github.com/fga-eps-mds/2020.1-Grupo2-wiki

# Copyright
# copyright: 'Copyright &copy; 2019 A Monitoria'

# Theme settings
theme:
#   logo: assets/img/logo/logo_icon.png
  # favicon:
  font:
    text: Roboto
    code: Roboto Mono
  feature:
    tabs: true
  language: 'pt'
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'purple'

# Content Menu
pages:
  - Inicio: index.md
nav:
  - Inicio: index.md
  - Termo de Abertura do Projeto: project_opening_term/project_opening_term.md
  - Documento de Visão: vision_document/vision_document.md
  - Documento de Arquitetura: architecture_document/architecture_document.md
  - Documento Suplementar: supplementary_document/supplementary_document.md
  - Plano de Gerenciamento de Comunicação: communication_plan/communication_plan.md
  - Plano de Gerenciamento de Riscos: risk_management/risk_management.md
  - Plano de Qualidade: quality_plan/quality.md
  - Plano de Gerenciamento de Custos: cost_document/cost_document.md
  - Política de Repositório: repository_politics/repository_politics.md
  - Product Backlog: product_backlog/product_backlog.md
  - Critérios de Aceitação: product_backlog/acceptance_criteria.md
  - EVM: evm/evm.md
  - RoadMap:
    - Roadmap de Produto: roadmap/product_roadmap.md
    - RoadMap de Papeis: roadmap/roles_roadmap.md
  - Prototipo: prototipo/prototipo.md
  - Sprints:
    - Sprint 0:
      - Planning: sprints/sprint0/planning.md
      - Results:  sprints/sprint0/results.md
    - Sprint 1:
      - Planning: sprints/sprint1/planning.md
      - Results:  sprints/sprint1/results.md
    - Sprint 2:
      - Planning: sprints/sprint2/planning.md

# Style
extra_css:
  - assets/style/extra.css

# Markdown extensions
# markdown_extensions:
#   - admonition
#   - codehilite:
#       linenums: true
#   - footnotes
#   - meta
#   - pymdownx.arithmatex
#   - pymdownx.betterem:
#       smart_enable: all
#   - pymdownx.caret
#   - pymdownx.critic
#   - pymdownx.details
#   - pymdownx.emoji:
#       emoji_generator: !!python/name:pymdownx.emoji.to_svg
#   - pymdownx.inlinehilite
#   - pymdownx.magiclink
#   - pymdownx.mark
#   - pymdownx.smartsymbols
#   - pymdownx.superfences
#   - pymdownx.tasklist:
#       custom_checkbox: true
#   - pymdownx.tilde
