# Project information
site_name: GaiaDex
site_description: Artefatos de MDS e EPS, 2020.1
site_author: GaiaDex
site_url: https://fga-eps-mds.github.io/2020.1-GaiaDex-wiki/

# Repository
repo_name: GaiaDex
repo_url: https://github.com/fga-eps-mds/2020.1-GaiaDex-wiki

# Copyright
# copyright: 'Copyright &copy; 2019 A Monitoria'

# Theme settings
theme:
  #   logo: assets/img/logo/logo_icon.png
  # favicon:
  font:
    text: Roboto
    code: Roboto Mono
  feature:
    tabs: true
  language: "pt"
  name: "material"
  palette:
    primary: "blue"
    accent: "purple"

# Content Menu
pages:
  - Inicio: index.md
nav:
  - Inicio: index.md

# Style // DONT ERASE THIS COMMENT [used in script "update_mkdocs_yml.py"]
extra_css:
  - assets/style/extra.css
